// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CopyID():Promise<string>;

export function GetBaseDir():Promise<string>;

export function GetStatus():Promise<Record<string, any>>;

export function RefreshID():Promise<Record<string, any>>;
