// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2) {
  return window['go']['tasks']['App']['Connect'](arg1, arg2);
}

export function CopyID() {
  return window['go']['tasks']['App']['CopyID']();
}

export function GetBaseDir() {
  return window['go']['tasks']['App']['GetBaseDir']();
}

export function GetStatus() {
  return window['go']['tasks']['App']['GetStatus']();
}

export function RefreshID() {
  return window['go']['tasks']['App']['RefreshID']();
}
